name: Build and Release Artifacts

on:
  push:
    branches: [ workflow-master ]
  pull_request:
    branches: [ workflow-master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  windows-build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo build --release
    - uses: actions/upload-artifact@v2
      with:
        name: librespot-win-x64.exe
        path: target/release/librespot.exe
    
  mac-build:
     runs-on: macos-latest
     steps:
     - uses: actions/checkout@v2
     - run: cargo build --release
     - uses: actions/upload-artifact@v2
       with:
        name: librespot-mac-x64
        path: target/release/librespot
        
  mac-arm64-build:
     runs-on: macos-latest
     steps:
     - uses: actions/checkout@v2
     - run: rustup target add aarch64-apple-darwin && cargo build --target=aarch64-apple-darwin --release
     - uses: actions/upload-artifact@v2
       with:
        name: librespot-mac-arm64
        path: target/
    
        
  linux-build:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
     - run: sudo apt-get update && sudo apt-get install libpulse-dev portaudio19-dev libasound2-dev libsdl2-dev gstreamer1.0-dev libgstreamer-plugins-base1.0-dev libavahi-compat-libdnssd-dev
            && cargo build --release
     - uses: actions/upload-artifact@v2
       with:
        name: librespot-linux-x64
        path: target/release/librespot
        
        
        
        
