name: Build on Mac.

on:
  push:
    branches: [ workflow-master ]
  pull_request:
    branches: [ workflow-master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: x64 Build
      run: cargo build --release
    - name: arm64 build
      run: rustup target add aarch64-apple-darwin && cargo build --target=aarch64-apple-darwin
    - uses: actions/upload-artifact@v2
      with:
        name: librespot
        path: target/release # or path/to/artifact
    - uses: actions/upload-artifact@v2
      with:
        name: librespot-x64
        path: target/release/librespot
    - uses: actions/upload-artifact@v2
      with:
        name: librespot-arm64
        path: target/aarch64-apple-darwin/debug/librespot
